#lang racket

(define (isvar e)
  (eq? (car e) 'VAR))
(define (name e)
  (cadr e))
(define (isconst e)
  (eq? (car e) 'QUOTE))
(define (number e)
  (cadr e))
(define (isnull S)
  (eq? (car S) 'SKIP))
(define (isassignment S)
  (eq? (car S) 'ASSIGN))
(define (lhs S)
  (cadr S))
(define (rhs S)
  (caddr S))

; ex 5.2
(define (assoc e omega)
  (omega e))

; ex 5.2
(define (update omega x y)
  (lambda (z)
    (if (eq? z x)
        y
        (omega z))))

(define (issum e)
  (eq? (car e) '+))
(define (operand1 e)
  (cadr e))
(define (operand2 e)
  (caddr e))
(define (simplevalue e)
  (cond
    ((isconst e) (number e))
    ((issum e) (+ (simplevalue (operand1 e)) (simplevalue (operand2 e))))
    (else 'ERROR)))
(define (iseq e)
  (eq? (car e) 'eq))

(define (first lst)
  (car lst))
(define (second lst)
  (cadr lst))
(define (issequence S)
  (eq? (car S) 'SEQUENCE))
(define (isconditional S)
  (eq? (car S) 'IF))
(define (iftest S)
  (cadr S))
(define (then S)
  (cadr S))
(define (else S)
  (caddr S))
(define (isloop S)
  (eq? (car S) 'LOOP))
(define (wtest S)
  (cadr S))
(define (wbody S)
  (caddr S))
(define (fourlist a b c d)
  (list a b c d))
(define (q x)
  (if (> x 100)
      x
      (q (* 2 x))))
(define (w y x q r)
  (if (>= r x)
      (w y x (+ q 1) (- r x))
      (fourlist y x q r)))
(define (fact n)
  (f n 1))
(define (f n m)
  (if (= n 0)
      m
      (f (- n 1) (* m n))))


(define (prev-val e n v)
  (if (eq? (caar n) (name e))
      (cdar v)
      (prev-val e (cdr n) (cdr v))))

; ex 5.2
(define (val e omega)
  (cond
    ((isvar e) (assoc (name e) omega))
    ((eq? (car e) 'prev) (prev-val (cadr e) omega))
    ((isconst e) (number e))
    ((issum e) 
     (+ (val (operand1 e) omega) (val (operand2 e) omega)))
    ((iseq e) 
     (eq? (val (operand1 e) omega) (val (operand2 e) omega)))
    (else 'ERROR)))

; ex 5.2
(define (effect S omega)
  (cond
    ((isnull S) omega)
    ((isassignment S) 
     (update omega (lhs S) (val (rhs S) omega)))
    ((issequence S) 
     (effect (second S) (effect (first S) omega)))
    ((isconditional S)
     (effect (if (val (iftest S) omega) 
                 (then S) 
                 (else S)) 
             omega))
    ((isloop S)
     (letrec ((w (lambda (omega)
                  (if (val (wtest S) omega)
                      (w (effect (wbody S) omega))
                      omega))))
       (w omega)))
    (else 'ERROR)))