#lang racket

; Converted into Racket
(define (square x)
  (* x x))
(define (reciprocal x)
  (/ 1 x))
(define (max x y)
  (if (>= x y)
      x
      y))
(define (largest x y z)
  (max (max x y) z))
(define (add x y)
  (+ x y))
(define (sub x y)
  (- x y))
(define (mul x y)
  (* x y))
(define (div x y)
  (/ x y))
(define (max-2 x y z)
  (set! z (if (>= x y) x y)))
(define (max-3 x y)
  (when (< x y)
    (set! x y)))
(define (max-4 x y)
  (if (>= x y)
      (set! x y)
      (set! x y)))
